cmd/stolon-pgbouncer/main.go
pkg/failover/server.go

Provide the option to just health check the failover endpoints, useful
if you want to validate everything is responsive in a test environment
etc.
Also check the PgBouncer health when running health checks. This makes
it easy to verify everything is ready before committing to a failover,
potentially pausing other working PgBouncers when you'll inevitably fail
due to a bad node.

failover --health-check-only, check PgBouncer

---

cmd/stolon-pgbouncer/main.go

Go represents durations as nanoseconds, whereas our metric is meant to
be in seconds.

Normalise Prometheus poll interval metrics

---

docker/stolon-development/pgbouncer/pgbouncer.ini
docker/stolon-development/pgbouncer/pgbouncer.ini.template
pkg/pgbouncer/integration/pgbouncer.go
pkg/pgbouncer/pgbouncer.go
pkg/pgbouncer/testdata/pgbouncer.ini.template

[^1]: https://github.com/lib/pq/issues/475
lib/pq sends extra_float_digits as a startup parameter [^1] whenever
initialising a Postgres connection. PgBouncer doesn't recognise this
parameter and will fail whenever you send it.
To prevent this, we ensured pgsql-cluster-manager would ban PgBouncer
configuration that didn't explicitly ignore this parameter. This is
likely irrelevant after we moved to pgx though, so we should remove this
constraint.

Don't require ignore_startup_parameters

---

cmd/stolon-pgbouncer/main.go

We label this metric with the relevant information, so don't need to set
the value to the hash of our cluster. I had initially suspected doing so
might be useful, but I've ended up multiplying this value by 0 and
adding 1 in every case I've used it, implying it's not useful at all.

stolon_pgbouncer_cluster_identifier = 1

---

cmd/stolon-pgbouncer/main.go

Prometheus discourages this type of behaviour, where you add dynamic
information into labels. In this case we'll have very few host values
that will appear here, so it doesn't matter so much if we do this.
We'll use this label to provide a recognisable textual host value in our
diagnostic dashboards, allowing us to easily list which pods are
connected to which host.

Expose keeper as label

---

pkg/acceptance/acceptance.go
pkg/failover/failover.go
pkg/stolon/stolon.go
pkg/stolon/stolon_test.go
pkg/stolon/suite_test.go

We don't want to perform a zero-downtime failover if we don't have at least two healthy keepers (excluding the master) in the cluster that can be promoted to master and sync.
CI will fail as I haven't published the new stolon-development image yet. Test locally and once approved we can publish it.

Check keepers healthy before failover

---

pkg/stolon/stolon.go

[DBStatus](https://github.com/sorintlab/stolon/blob/a0ca05e92cd9fefc6d6a34c042bffadc3b3ced7e/internal/cluster/cluster.go#L658) doesn't track external synchronous standbys, only the [DBSpec](https://github.com/sorintlab/stolon/blob/a0ca05e92cd9fefc6d6a34c042bffadc3b3ced7e/internal/cluster/cluster.go#L631) does.

Fix external sync marshalling

---

cmd/stolon-pgbouncer/main.go
docker/observability/grafana/dashboards/stolon-pgbouncer.json
docker/observability/prometheus/rules.yml
pkg/streams/filter.go

I've significantly rejigged the alerts now, so I'm going to create a checklist like we had in anu for whoever comes to review, only difference being that people should test locally against docker-compose.
Run `docker-compose up` before any of these steps.
- This was delayed by about 1 minute - maybe because of the `evaluation_interval`?
- Interestingly, I also saw the `StolonPgBouncerStaleStore` alert fire
This isn't testable in our test setup, as we don't have multiple stolon-pgbouncers. Worth doing though, just to check that the pgbouncer in shutdown is stuck in a stale keeper state. Eyeballing the alert to check it would function correctly if we had multiple PgBouncers would also be :aces:

Don't expect PgBouncer to be reloaded

---

cmd/stolon-pgbouncer/main.go
docker/observability/grafana/dashboards/stolon-pgbouncer.json
docker/observability/prometheus/rules.yml

As we add metrics to stolon as a whole, it makes sense for every stolon
component to output this metric to properly join between each time
series. In this case, we should un-namespace this metric so it can share
the name across the stolon codebase.

Un-namespace cluster identifier

---

Makefile
README.md

This ensures that starting the playground is as simple as running `make
docker-compose` - without having to explicitly build the Linux binary
first.

Add a make target for docker-compose

---

Makefile
cmd/stolon-pgbouncer/main.go
docker-compose.yml
docker/observability/grafana/dashboards/stolon-keeper.json
docker/observability/grafana/dashboards/stolon-pgbouncer.json
docker/observability/prometheus/rules.yml
docker/stolon-development/Dockerfile

https://github.com/sorintlab/stolon/pull/639
Stolon maintainers reckon the store_prefix isn't necessary to have in
our metric labels. We've removed this upstream in the keeper, so we
should adjust our stolon-pgbouncer binaries to match.
This commit makes the change and bumps our development image to
recognise it, inclusive of updating dashboards and alerts.

Drop store_prefix label from metrics

---

docker/stolon-development/stolon/specification.json

This used the wrong key, it's meant to be role.

Amend cluster specification: role

---

docker/observability/prometheus/rules.yml

If a Prometheus fails to scrape for a couple of intervals, a threshold
of just 1m will cause us to alert when there is no reason for alarm.
This increases the thresholds to ensure we get alerted only when
something is genuinely wrong with the cluster.

Increase alert thresholds

---

cmd/stolon-pgbouncer/main.go
pkg/failover/failover.go

Etcd appears to check the grpc authorization header, so re-using the
authed client context will cause etcd to reject requests. This has the
failover package handle annotating these headers, but is pending the
refactor to get status to use the same method.

Don't use authed client context for etcd

---

cmd/stolon-pgbouncer/main.go
pkg/etcd/stream.go

Instead of terminating whenever we receive an error from the etcd
watcher, instead retry indefinitely on the assumption that this will
eventually succeed. This prevents us going into a termination state from
a recoverable etcd error, and we can rely on the downstream stolon proxy
to ensure we never connect to a bad (non-primary) node.
We also make our watcher more fussy, by rejecting any watch streams that
have ended up coming from a non-leader etcd node. This should ensure we
don't ever get stuck speaking to an etcd node that is partitioned from
the leader and not try to reconnect to a more up-to-date member.

Retry watch indefinitely

---

cmd/stolon-pgbouncer/main.go

Apply the kitlog.With in the correct location to ensure the
DefaultCaller function can correctly identify call location.

Fix caller log key

---

Makefile
pkg/etcd/stream.go

@hmac this probably fixes most of the issues you had with the goto? Maybe?
After a discussion about the metrics of gotos, I think this might be a
better expression of the codes aims. The benefits are that label usage
is scoped to your current method and can't jump around anywhere, and you
have a code brace {} that encloses all the label usage.

Locally scoped break label

---

cmd/stolon-pgbouncer/main.go
pkg/acceptance/acceptance.go

Ensure that even when the pauser is violently terminated, such as when
being OOM-killed, bringing the process back up will resume PgBouncer and
re-enable queries.

Resume PgBouncer on pauser start-up

---

Makefile
docker-compose.yml
docker/observability/grafana/dashboards/stolon-keeper.json
docker/observability/grafana/dashboards/stolon-pgbouncer.json
docker/observability/prometheus/prometheus.yml
docker/observability/prometheus/rules.yml
docker/stolon-development/Dockerfile
docker/stolon-development/supervisord-pgbouncer.conf
docker/stolon-development/supervisord.conf

Modify the stolon development image to install the GC fork of the
pgbouncer-exporter then add it to the pgbouncer and keeper machines. Get
Prometheus scraping the PgBouncer metrics and exposing the active client
connections in the dashbaord.
Also switch our use of metric labels to assume instance is a human
readable fully-qualified hostname of the scrape target. This simplifies
several series joins.
---
I've tested this by triggering a new rollout of the staging stolon-pgbouncer deployment to verify the metrics work correctly (`stolon-main-pgbouncer-backend-default`). Watching one of the rollouts, you'll see the following:

o11y: Expose PgBouncer metrics

---

cmd/stolon-pgbouncer/main.go

While not entirely secure, env vars are slightly better than flag
parameters (they're not visible by all users) and they don't need to be
escaped for your shell.

PgBouncer password from PGBOUNCER_PASSWORD

---

Makefile
docker-compose.yml
docker/stolon-development/Dockerfile
docker/stolon-development/stolon/init.bash

This commit changes our development setup to entirely use the GC fork of
stolon, not just the keeper. This makes more sense than just installing
the keeper, a decision we took when we believed we'd only modify stolon
once or twice.

Use GC stolon binaries, not just keeper

---

cmd/stolon-pgbouncer/main.go

This commit changes the way we manage PgBouncer by waiting until a valid
keeper host has been received before starting the PgBouncer process.
This prevents PgBouncer from coming up before we have a valid
destination and should allow readiness health checks to continue
checking for the 6432 tcp port to detect if a pod is route-able.

Boot PgBouncer after keeper host received

---

docker/observability/prometheus/rules.yml

Using instance as a join label can result in many-to-many matches when
the same IP is scraped for many exporters. Using ignore is Prometheus
best practice for building robust rules and removes this concern.

Fix many-to-many Prometheus rule evaluation

---

Makefile
docker-compose.yml
docker/observability/grafana/dashboards/stolon-sentinel.json
docker/observability/prometheus/prometheus.yml
docker/stolon-development/Dockerfile

Scrape the sentinel metrics endpoint (GC PR gocardless/stolon#10; Upstream PR sorintlab/stolon#656) and add a dashboard to the Grafana setup.

Add sentinel metrics to playground

---

cmd/stolon-pgbouncer/main.go
docker/observability/prometheus/rules.yml

This will enable polymorphic alerts over all the stolon components while
exposing a component label that can help identify which has gone wrong.

Add component label to stolon_cluster_identifier

---

Dockerfile
Makefile
circle.yml
docker/circleci/Dockerfile
docker/stolon-development/Dockerfile

This includes a pgbouncer version bump from 1.9 to 1.10, and should
confirm compatibility.

Bump docker images for recent dependencies

---

cmd/stolon-pgbouncer/main.go
docker/stolon-development/stolon/specification.json
go.mod
go.sum
pkg/acceptance/acceptance.go
pkg/failover/failover.go
pkg/stolon/stolon.go
pkg/stolon/stolon_test.go
vendor/github.com/buger/jsonparser/.gitignore
vendor/github.com/buger/jsonparser/.travis.yml
vendor/github.com/buger/jsonparser/Dockerfile
vendor/github.com/buger/jsonparser/LICENSE
vendor/github.com/buger/jsonparser/Makefile
vendor/github.com/buger/jsonparser/README.md
vendor/github.com/buger/jsonparser/bytes.go
vendor/github.com/buger/jsonparser/bytes_safe.go
vendor/github.com/buger/jsonparser/bytes_unsafe.go
vendor/github.com/buger/jsonparser/escape.go
vendor/github.com/buger/jsonparser/parser.go
vendor/modules.txt

We need failover to function within this limit reliably, so reduce the
expiry in our tests so we can't merge anything that violates this
constraint.

Reduce failover time to acceptable levels

---

circle.yml

This was a nice idea that turned out to be a bit rubbish. A better plan
is to fail CI until someone handles this themselves.

Don't automatically push new go mod vendor

---

cmd/stolon-pgbouncer-acceptance/main.go

CircleCI is sometimes slow at starting up the cluster and we fail in
CI as result. This bumps the default eventually timeout to 2 minutes
to give CircleCI extra time to bring the cluster up and into a
healthy state before starting our acceptance tests.

Increase acceptance tests timeout

---

Dockerfile
Makefile
circle.yml
docker-compose.yml
docker/base/Dockerfile
docker/circleci/Dockerfile
docker/stolon-development/Dockerfile

This refreshes our base images, particularly important given pgBouncer
is now at 1.11.0.

Bump docker dependencies

---

Dockerfile
Makefile
circle.yml
docker-compose.yml
docker/circleci/Dockerfile
docker/stolon-development/Dockerfile

We install stolon from the GoCardless fork, so don't keep the old
install method as this is misleading.

Remove unused stolon install

---

docker/observability/grafana/dashboards/stolon-keeper.json

When performing maintenance on stolon-keepers, it's useful to know the
current uptime and whether the keeper requires a restart. This adds
those fields, making it easy for an operator to tick each keeper off a
checklist (they go green when fixed).

stolon-keeper: uptime, needs_restart
